title: Gepetto's test site
description: A website to check github pages, jekyll & bootstrap 4
baseurl: ""
url: "https://nim65s.github.io"
twitter_username: nim65s
github_username:  nim65s
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE

category_list:
  - name: Getting Started
    icon: graduation-cap
  - name: Documentation
    icon: book
  - name: Development
    icon: wrench
  - name: Support
    icon: question-circle
